import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'background':                '#fff8ef',
        'surface':                   '#fff8ef',
        'surface-bright':            '#fff8ef',
        'surface-dim':               '#dfd9d0',
        'surface-container-lowest':  '#ffffff',
        'surface-container-low':     '#f9f3ea',
        'surface-container':         '#f3ede4',
        'surface-container-high':    '#ede7de',
        'surface-container-highest': '#e8e2d9',
        'surface-variant':           '#e8e2d9',
        'on-background':             '#1d1b16',
        'on-surface':                '#1d1b16',
        'on-surface-variant':        '#4e453e',
        'primary':                   '#322214',
        'primary-container':         '#4a3728',
        'primary-fixed':             '#fbddc7',
        'primary-fixed-dim':         '#dec1ac',
        'on-primary':                '#ffffff',
        'on-primary-container':      '#bba08c',
        'on-primary-fixed':          '#28180b',
        'on-primary-fixed-variant':  '#574333',
        'inverse-primary':           '#dec1ac',
        'secondary':                 '#55624e',
        'secondary-container':       '#d6e4ca',
        'secondary-fixed':           '#d9e7cd',
        'secondary-fixed-dim':       '#bdcbb2',
        'on-secondary':              '#ffffff',
        'on-secondary-container':    '#596652',
        'on-secondary-fixed':        '#131e0e',
        'on-secondary-fixed-variant':'#3e4a37',
        'tertiary':                  '#3c1d09',
        'tertiary-container':        '#56321d',
        'tertiary-fixed':            '#ffdbca',
        'tertiary-fixed-dim':        '#f2bb9d',
        'on-tertiary':               '#ffffff',
        'on-tertiary-container':     '#ce9a7e',
        'on-tertiary-fixed':         '#301303',
        'on-tertiary-fixed-variant': '#643d27',
        'outline':                   '#80756d',
        'outline-variant':           '#d2c4bb',
        'error':                     '#ba1a1a',
        'error-container':           '#ffdad6',
        'on-error':                  '#ffffff',
        'on-error-container':        '#93000a',
        'surface-tint':              '#705a49',
        'inverse-surface':           '#33302a',
        'inverse-on-surface':        '#f6f0e7',
      },
      fontFamily: {
        serif:    ['var(--font-newsreader)', 'Georgia', 'serif'],
        sans:     ['var(--font-manrope)', 'system-ui', 'sans-serif'],
        headline: ['var(--font-newsreader)', 'Georgia', 'serif'],
        body:     ['var(--font-manrope)', 'system-ui', 'sans-serif'],
        label:    ['var(--font-manrope)', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '8px',
        lg:      '12px',
        xl:      '16px',
        '2xl':   '24px',
        '3xl':   '32px',
        '4xl':   '40px',
        '5xl':   '60px',
        full:    '9999px',
      },
    },
  },
  plugins: [],
}

export default config
